<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PruIT_CMDB_ITSM.Client\PruIT_CMDB_ITSM.Client.csproj" />
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

</Project>
